### ISSUE TITLE
Implement service layer in the backend application 

### ISSUE THREAD

**Issue by hoosengold** [hoosengold/clean_code_development_course#39]
# Task Description
- Implement the service layer in the backend. It should connect the REST and the persistence layer. Make sure the be consistent with the 2 other implemented layers.
- Write the corresponding unit tests.

# Linked User Story (-ies)
- #16 

# Subtasks
- [x] Implement DAO pattern.
- [x] Connect the layers.
- [x] Write unit tests.
